### PR TITLE
Simple fix for the path name to package conversion for windows

### PR DESCRIPTION
**Pull request by mattys101**
The `replaceAll` didn't like it when it received the backslash path separator on Windows.
Changed it to simply `replace` using characters.

### CODE REVIEW

**Comment by jamesladd** [comment]
Seems to think the whole files has changed - are we out of whack w tabs v spaces?

Which lines did you change?

**Comment by kdriedger** [comment]
Line endings?
https://help.github.com/articles/dealing-with-line-endings/

**Comment by mattys101** [comment]
Line endings would probably do it. Although wouldn't have thought Eclipse with the Git plugin would cause that kind of issue. :-(

The actual changed line was 175.

I'll check out that link and make sure my configuration doesn't do that again. Sorry.

**Comment by mattys101** [comment]
Should I try to fix this at my end and then redo the pull request? If so, what's the best way? I'm not a huge fan of rewriting the commit history and not 100% sure how to do it either

**Comment by jamesladd** [comment]
Happy if you make a new pull request and delete the old one

**Comment by mattys101** [comment]
Killing this off as I (think) I have fixed the line endings.

**Comment by mattys101** [comment]
Ok, fixed it, but it appears to have attached to the same pull request? (which is a little scary, aren't the commits associated with a unique identifier? Looking at the changes it appears to be correct with only a single line change.)

**Pull request merged**
